// mern-auth-app\server\models\Form.js
const mongoose = require("mongoose");

// Schema for individual form fields (e.g., text inputs, checkboxes)
const fieldSchema = new mongoose.Schema(
  {
    id: { type: String, required: true }, // UUID generated by frontend
    type: { 
      type: String, 
      required: true,
      enum: ["text", "email", "textarea", "select", "radio", "checkbox"] // Optional: Restrict types for safety
    },
    label: { type: String, required: true },
    required: { type: Boolean, default: false },
    // For Select/Radio inputs (future proofing)
    options: { 
      type: [String], 
      default: [] 
    }, 
  },
  { _id: false } // Prevent Mongoose from creating a unique _id for every field definition
);

const formSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    fields: { 
      type: [fieldSchema], 
      default: [] 
    },
    // The Admin (Organization) who owns this form
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Form", formSchema);